name: macOS user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: brew install meson
    - name: Meson setup
      run: meson setup build -Dslh_dsa_ascon_128s=enabled -Dslh_dsa_ascon_128f=enabled
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build --suite regression
