name: Linux user space CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson gcovr doxygen graphviz
    - name: Meson setup
      run: meson setup build -Db_coverage=true -Dslh_dsa_ascon_128s=enabled -Dslh_dsa_ascon_128f=enabled -Dsecure_execution=enabled
    - name: Meson compile
      run: meson compile -C build
    - name: Meson test
      run: meson test -C build
    #- name: Generate test coverage report
    #  run: ninja coverage-html -C build
    #- name: Archive code coverage results
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: code-coverage-report
    #    path: build/meson-logs/coveragereport
